# Generated by Django 5.2.8 on 2025-11-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidos',
            name='iframe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
