# Generated by Django 5.2.8 on 2025-11-12 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contenido',
            new_name='contenidos',
        ),
    ]
